SCREEN_SIZE_X, SCREEN_SIZE_Y = 800, 500
BACKGROUND_FADE_SPEED = 30
PADDLE_SPEED = 5

TRANSITION_FADING = False

LEFT_CLICKABLE = True

GAME_START_INSTRUCTIONS = True

# SETTINGS #

MusicVolume = 0.5
SFXVolume = 0.5

SpecialEffectsEnabled = True